// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5iczrojqSF9Gm4OUhGqMELE-B-NrFNwU',
    appId: '1:104443034677:web:df5e85efd613f350ca457c',
    messagingSenderId: '104443034677',
    projectId: 'assignment-c68b4',
    authDomain: 'assignment-c68b4.firebaseapp.com',
    storageBucket: 'assignment-c68b4.appspot.com',
    measurementId: 'G-18ECRN1M5V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbL5Hp-3jNd7jILcQ7RjQiLbfAa3F-b9M',
    appId: '1:104443034677:android:b0ba0c937d20ab41ca457c',
    messagingSenderId: '104443034677',
    projectId: 'assignment-c68b4',
    storageBucket: 'assignment-c68b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuLXqiGKgXas1_raetzioLxT6XEd98MBI',
    appId: '1:104443034677:ios:0d21155384120065ca457c',
    messagingSenderId: '104443034677',
    projectId: 'assignment-c68b4',
    storageBucket: 'assignment-c68b4.appspot.com',
    iosClientId: '104443034677-75mbe95gc5rbaqpie396nu1iokm6g5u4.apps.googleusercontent.com',
    iosBundleId: 'com.assignment.buddyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuLXqiGKgXas1_raetzioLxT6XEd98MBI',
    appId: '1:104443034677:ios:0d21155384120065ca457c',
    messagingSenderId: '104443034677',
    projectId: 'assignment-c68b4',
    storageBucket: 'assignment-c68b4.appspot.com',
    iosClientId: '104443034677-75mbe95gc5rbaqpie396nu1iokm6g5u4.apps.googleusercontent.com',
    iosBundleId: 'com.assignment.buddyapp',
  );
}
